name = "resvg"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-26"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
